# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386795b7847e4a5dc0384fe6b551cae4c32d43cc497909ed5cd4c290edd7c46c2de5904b897b5196b888e375d5ee74b2a8562596e19332387233c2ba8cfb2a0c

test:
  secret_key_base: 6b16eb790314f43ba2a242b95740d3995b470221c93b261a8abd1d336ff901ba282a04c6581ef17f6d6bf8c2b8dbb8416eea7c16760c40d522a8967b086479c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
